services:
  notes-api:
    container_name: notes-api
    restart: always
    environment:
      - NODE_ENV=Production
    build:
      context: ./

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy_service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  coddy_config: